version: '3.9'

services:
  app:
    image: 'lucid_wilson'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    image: 'postgres'
    container_name: postgres_new
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: